### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by benedekrozemberczki** [guzmanlopez/montevideo-bus-forecast#1]
Hi there,

The dataset in the repo is pretty cool. Do you want to add it as a contributed dataset to the library and be on the research paper as a contributing author?

Bests,

Benedek

**Comment by guzmanlopez** [comment]
Hi @benedekrozemberczki,

First, I want to say thanks for your amazing work with the PyTorch Geometric Temporal extension library that I'm currently using.
Also, I'm very glad that you appreciate the dataset because It took me a lot of time to build it 😅. It will be great to add the dataset to your library and be a contributing author on the research paper. I have just pushed a new python file to my repo that contains a  class called [MontevideoBusDatasetLoader](https://github.com/guzmanlopez/montevideo-bus-forecast/blob/main/src/modeling/montevideo_bus_dataset.py ) to load the dataset based on the ones I saw in your repository. Maybe I can create a PR in your repo adding the data and the class to load it. 

Best, 

Guzman

**Comment by benedekrozemberczki** [comment]
Feel free to open a PR, I can create the tests, integration and docs.

**Comment by benedekrozemberczki** [comment]
Hi there,

I will add the dataset loader tonight and create a loader.

Bests,

Benedek

**Comment by guzmanlopez** [comment]
Hi Benedek,

I'm working in the PR and I can send it to you in ~2 hours or less. 

Best,
Guzmán
